### ISSUE TITLE
Add vendor dependency to README.md

### ISSUE THREAD

**Issue by hexeberlin** [zalando-zmon/opentracing-utils#46]
The libraries of the specific vendors (lightstep, instant, jaeger) are not part of `dependencies.txt` of `opentracing-utils` and have to be added to the dependencies of the application which is using `opentracing-utils` (otherwise it will fail, e.g. here https://app.eu.scalyr.com/y/7pqX2nx43k2). It would be nice to mention it in the README in the [Usage](https://github.com/zalando-zmon/opentracing-utils#usage) part.

**Comment by pitr** [comment]
would you be able to open a PR to add them to README?

**Comment by pitr** [comment]
thank you!
